(function(){var h=window.Element.prototype,k=h.matches||h.matchesSelector||h.webkitMatchesSelector||h.mozMatchesSelector||h.msMatchesSelector||h.oMatchesSelector;function m(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||n(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||n(a,d))return!0}return!1}function n(a,b){if("string"!=typeof b)return!1;if(k)return k.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}
function q(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function r(a,b,c){function d(a){var d;if(f.composed&&"function"==typeof a.composedPath)for(var g=a.composedPath(),e=0,p;p=g[e];e++)1==p.nodeType&&m(p,b)&&(d=p);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(q(d)),g=0;e=d[g];g++)if(m(e,b)){d=e;break a}d=void 0}d&&c.call(d,a,d)}var g=document,f={composed:!0,h:!0};f=void 0===f?{}:f;g.addEventListener(a,d,f.h);return{g:function(){g.removeEventListener(a,d,f.h)}}}
function t(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(0===a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var u=/:(80|443)$/,v=document.createElement("a"),w={};
function x(a){a=a&&"."!=a?a:location.href;if(w[a])return w[a];v.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return x(v.href);var b="80"==v.port||"443"==v.port?"":v.port;b="0"==b?"":b;var c=v.host.replace(u,"");return w[a]={hash:v.hash,host:c,hostname:v.hostname,href:v.href,origin:v.origin?v.origin:v.protocol+"//"+c,pathname:"/"==v.pathname.charAt(0)?v.pathname:"/"+v.pathname,port:b,protocol:v.protocol,search:v.search}}
function y(a,b,c,d,g,f){if("function"==typeof d){var e=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,g,f);e(c)}}}return z({},a,b)}function A(a,b){var c=t(a),d={};Object.keys(c).forEach(function(a){if(0===a.indexOf(b)&&a!=b+"on"){var f=c[a];"true"==f&&(f=!0);"false"==f&&(f=!1);a=B(a.slice(b.length));d[a]=f}});return d}function C(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}
var z=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;for(var g=c.length;d<g;d++){var f=Object(c[d]),e;for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(a[e]=f[e])}return a};function B(a){return a.replace(/[-_]+(\w?)/g,function(a,c){return c.toUpperCase()})}
function D(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var E={l:1,m:2,o:3,u:4,v:5,j:6,w:7,A:8,B:9,s:10,i:11},F=Object.keys(E).length;
function G(a,b){a.set("\x26_av","2.4.1");var c=a.get("\x26_au");c=parseInt(c||"0",16).toString(2);if(c.length<F)for(var d=F-c.length;d;)c="0"+c,d--;b=F-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}
function H(a,b){var c=this;G(a,E.j);window.addEventListener&&(this.a=z({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.c=a,this.f=this.f.bind(this),this.b={},this.a.events.forEach(function(a){c.b[a]=r(a,c.a.linkSelector,c.f)}))}
H.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackOutboundLink(b,x)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),g=x(d);g={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:g.href};var f=z({},this.a.fieldsObj,A(b,this.a.attributePrefix)),e=y(g,f,this.c,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.c.send("event",e);else{var l=function(){window.removeEventListener("click",
l);if(!a.defaultPrevented){a.preventDefault();var b=e.hitCallback;e.hitCallback=C(function(){"function"==typeof b&&b();location.href=d})}c.c.send("event",e)};window.addEventListener("click",l)}}};H.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};H.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].g()})};D("outboundLinkTracker",H);
function I(a,b){var c=this;G(a,E.i);window.addEventListener&&(this.a=z({events:["click"],linkSelector:"a, area",shouldTrackDownloadDocument:this.shouldTrackDownloadDocument,fieldsObj:{},attributePrefix:"ga-"},b),this.c=a,this.f=this.f.bind(this),this.b={},this.a.events.forEach(function(a){c.b[a]=r(a,c.a.linkSelector,c.f)}))}
I.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackDownloadDocument(b,x)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),g=x(d);g={transport:"beacon",eventCategory:"Document Download",eventAction:a.type,eventLabel:g.href};var f=z({},this.a.fieldsObj,A(b,this.a.attributePrefix)),e=y(g,f,this.c,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.c.send("event",e);else{var l=function(){window.removeEventListener("click",
l);if(!a.defaultPrevented){a.preventDefault();var b=e.hitCallback;e.hitCallback=C(function(){"function"==typeof b&&b();location.href=d})}c.c.send("event",e)};window.addEventListener("click",l)}}};I.prototype.shouldTrackDownloadDocument=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname==location.hostname&&"http"==b.protocol.slice(0,4)&&("."==b.pathname.slice(-4,-3)||"."==b.pathname.slice(-5,-4))};I.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].g()})};
D("documentDownloadTracker",I);})();
//# sourceMappingURL=autotrack.js.map